name: archetype
packages:
  - app
  - locator
  - core/*
  - framework/*
  - feature/*

scripts:
  build_runner:
    description: 'promp in which packages, with build_runner as a dependency, run build_runner. (*) -> run on all'
    run: "flutter packages pub run build_runner build --delete-conflicting-outputs"
    exec:
      orderDependents: true
      concurrency: 1
    packageFilters:
      dependsOn: build_runner

command:
  bootstrap:
    environment:
      sdk: ^3.2.5
      flutter: ^3.0.0

    dependencies:
      flutter:
        sdk: flutter
      flutter_bloc: ^8.1.3
      equatable: ^2.0.5
      go_router: ^13.1.0
      injectable: ^2.3.2
      get_it_mixin: ^4.2.2
      retrofit: ^4.1.0
      dio: ^5.4.0
      logger: ^2.0.2+1
      isar: ^3.1.0+1
      isar_flutter_libs: ^3.1.0+1

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^2.0.0
      injectable_generator: ^2.4.1
      build_runner: ^2.4.8
      retrofit_generator: ^8.1.0
      isar_generator: ^3.1.0+1

      lints: ^2.1.0
      test: ^1.24.0
