name: database
publish_to: 'none'

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  locator:
    path: '../../locator'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
