name: app
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.1.0
  flutter_bloc: ^8.1.3

  locator:
    path: '../locator'
  domain:
    path: '../core/domain'
  data:
    path: '../core/data'
  design_system:
    path: '../core/design_system'
  network:
    path: '../framework/network'
  database:
    path: '../framework/database'

  # features
  sample:
    path: '../feature/sample'
  detail:
    path: '../feature/detail'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
