name: network
publish_to: 'none'

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  retrofit: ^4.1.0
  dio: ^5.4.0
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
